---
title: "2 Asset MVO Practice"
author: "Bouke Spoelstra"
date: "2024-10-21"
output: html_document
---

A hedge fund is allocating 50M dollars to a politically hedged subversive ETF strategy. Basically, they're betting that some combination of assets that track democrats' and republicans' trades will outperform the market. For our analysis of optimal combination, we will use the Unusual Whales Republican ETF $KRUZ and the corresponding one for Democrats $NANC.

Questions:
1. How much of the fund should be allocated to each asset?
2. Construct the portfolio possibilities curve (efficient frontier) by assuming no short sales and by minimizing the risk of the portfolio (GMV)
3. Construct the portfolio possibilities curve assuming that short sale is allowed.
4. Graph the two curves together distinguishing them with different colors.
5. Graph CAL and find the point of tangency.

```{r}
# Install and load the quantmod package
if(!require(quantmod)) {
    install.packages("quantmod")
}
library(quantmod)


# Get the data for the last 1 year
assets <- getSymbols(c("KRUZ","NANC","^TNX"),.GlobalEnv, src = "yahoo", from = Sys.Date() - 365, to = Sys.Date(), return.class = "timeSeries")
assets

# Convert prices to returns
rKRUZ <- na.omit(diff(log(KRUZ$KRUZ.Adjusted)))
rNANC <- na.omit(diff(log(NANC$NANC.Adjusted)))
rTNX <- na.omit(TNX$TNX.Adjusted / 25200)

# Compute mean returns
rKRUZ_mean <- mean(rKRUZ)
rNANC_mean <- mean(rNANC)

# Compute variance of returns
rKRUZ_var <- var(rKRUZ)
rNANC_var <- var(rNANC)

# Compute covariance of returns
rKRUZ_rNANC_cov <- cov(rKRUZ, rNANC)

# Construct variance-covariance matrix
var_cov_values <- round(c(rKRUZ_var, rKRUZ_rNANC_cov, rKRUZ_rNANC_cov, rNANC_var),5)
var_cov_matrix = matrix(var_cov_values, 
nrow=2, 
ncol=2) 
rownames(var_cov_matrix) <- c("KRUZ", "NANC")
colnames(var_cov_matrix) <- c("KRUZ", "NANC")

# Construct risk premium matrix
rTNX_mean <- mean(rTNX)

KRUZ_risk_premium <- rKRUZ_mean - rTNX_mean
NANC_risk_premium <- rNANC_mean - rTNX_mean

risk_premium_matrix = matrix(round(c(KRUZ_risk_premium,NANC_risk_premium),5), 
nrow=2, 
ncol=1) 
rownames(risk_premium_matrix) <- c("KRUZ", "NANC")
colnames(risk_premium_matrix) <- c("Rp")

# Display asset return statistics
cat("The (monthly) expected rate of returns for $KRUZ and $NANC are ", round(rKRUZ_mean*100,2), "% and ", round(rNANC_mean*100,2), "%, respectively.\n\n", sep="")
cat("The variance-covariance matrix looks as follows:\n\n")
print(var_cov_matrix)
cat("\n\nThe risk premium matrix looks as follows:\n\n")
print(risk_premium_matrix)


## Optimum weights ##

# Get inverse of variance-covariance matrix
var_cov_matrix_inv <- solve(var_cov_matrix)

# Multiply inverse matrix by risk premium vector
inv_times_rp <- var_cov_matrix_inv %*% risk_premium_matrix

# Get the sum of inverse * Rp, (z)
lambda <- sum(inv_times_rp)

# Calculate optimum weights
KRUZ_weight <- inv_times_rp[1]/lambda
NANC_weight <- inv_times_rp[2]/lambda

cat("The optimum weight for $KRUZ using MPT is: ", round(KRUZ_weight*100,2), "%\n", sep = "")
cat("The optimum weight for $NANC using MPT is: ", round(NANC_weight*100,2), "%\n", sep = "")

## Calculate the CAL equation and graph the CAL and the efficient frontier. ##
# Return, variance and covariance of optimum portfolio
r_optimum <- KRUZ_weight*rKRUZ_mean+NANC_weight*rNANC_mean
var_optimum <- KRUZ_weight^2*rKRUZ_var+NANC_weight^2*rNANC_var+2*KRUZ_weight*NANC_weight*rKRUZ_rNANC_covar
std_optimum <- sqrt(var_optimum)

# Input risk free rate
Rf <- rTNX_mean

# Calculate the CAL line
CAL_slope <- (r_optimum-Rf) / std_optimum
CAL <- function(X) { Rf + CAL_slope * X }

## Graph efficient frontier ##

# Construct portfolio using the two stocks.
# Read expected returns, variance, and covariance:
r1_sample_mean <-  rKRUZ_mean
r2_sample_mean <-  rNANC_mean
var1 <-  rKRUZ_var
var2 <-  rNANC_var
cov_12 <-  rKRUZ_rNANC_covar

#Short sales NOT allowed:
weight_a_1 <- seq(0, 1, 0.1)
weight_a_2 <- 1-weight_a_1
rPortfolio_a <- weight_a_1*r1_sample_mean+weight_a_2*r2_sample_mean
var_Portfolio_a <- weight_a_1^2*var1+weight_a_2^2*var2+2*weight_a_1*weight_a_2*cov_12
sd_Portfolio_a <- var_Portfolio_a^0.5

#Short sales allowed:
weight_b_1 <- seq(-2,2, 0.1)
weight_b_2 <- 1-weight_b_1
rPortfolio_b <- weight_b_1*r1_sample_mean+weight_b_2*r2_sample_mean
var_Portfolio_b <- weight_b_1^2*var1+weight_b_2^2*var2+2*weight_b_1*weight_b_2*cov_12
sd_Portfolio_b <- var_Portfolio_b^0.5

# Plot the two portfolio possibilities curves:
# Red, short sales allowed. Green,  short sales not allowed.
plot(sd_Portfolio_b, rPortfolio_b, col="red", xlab="Portfolio standard deviation", ylab="Portfolio expected return", pch=16, xlim=c(0.006, 0.012), ylim=c(0.0009,0.0016))
points(sd_Portfolio_a, rPortfolio_a, col="green", pch=16)
abline(h = 0, v = 0, lty = 3)

# plot CAL tangent line
plot.function(CAL, add = TRUE, col="black", lwd = 4)

# Display answer - investment amount in each
investmentAmount <- 50000000
cat("Based on the optimum weights, with no short sales we would allocate $", round(investmentAmount*KRUZ_weight,2), " in $KRUZ stock, and $", round(investmentAmount*NANC_weight,2), " in $NANC stock. \n\n", sep="")
```

